extends SceneTree

const State = preload("res://scripts/restaurant_state.gd")

func _initialize() -> void:
	var game: RestaurantState = State.new()
	game.save_path = "user://test_restaurant_v1.json"
	assert(game.recipes.size() == 2)
	assert(game.phase == "PREPARATION")
	game.start_shift()
	assert(game.phase == "OPEN")
	assert(game.customer_stage == "entering")
	assert(game.order == "tteokbokki")
	assert(game.begin_cooking())
	assert(not game.begin_cooking())
	assert(game.acquire_stove(1))
	assert(not game.acquire_stove(2))
	game.release_stove(2)
	assert(game.station_owner == 1)
	assert(game.gather("rice_cake"))
	assert(not game.gather("rice_cake"))
	assert(game.add_carried())
	assert(game.inventory["rice_cake"] == 2)
	assert(game.gather("fish_cake"))
	assert(not game.add_carried())
	for i in range(4): assert(game.chop(0.25))
	assert(game.add_carried())
	assert(game.gather("gochujang"))
	assert(game.add_carried())
	assert(game.ingredients_complete())
	game.set_heat(0.68)
	for i in range(600):
		game.tick(0.05)
		game.stir(0.01)
	assert(float(game.session["doneness"]) >= 0.4)
	assert(game.customer_stage == "seated")
	for i in range(3): assert(game.plate(0.35))
	assert(game.dish["recipe"] == "tteokbokki")
	assert(game.station_owner == 0)
	assert(not game.plate(0.35))
	assert(game.serve())
	assert(game.customer_stage == "leaving")
	assert(not game.serve())
	assert(game.served == 1)
	assert(game.order == "ramyeon")
	assert(game.money > 30)
	_cook_order(game)
	assert(game.serve())
	assert(game.served == 2)
	_cook_order(game)
	assert(game.serve())
	assert(game.phase == "RESULTS")
	assert(game.customer_stage == "absent")
	assert(game.served == 3)
	assert(not game.serve())
	game.start_shift()
	assert(game.day == 2 and game.phase == "OPEN" and game.served == 0)
	assert(game.save_game())
	var restored: RestaurantState = State.new()
	restored.save_path = game.save_path
	assert(restored.load_game())
	assert(restored.money == game.money)
	assert(restored.inventory == game.inventory)
	assert(not restored.restock("invalid"))
	print("STATE TESTS PASSED")
	quit()

func _cook_order(game: RestaurantState) -> void:
	assert(game.begin_cooking())
	var recipe: Dictionary = game.recipes[game.order]
	for item in recipe["ingredients"]:
		assert(game.gather(item))
		if item == recipe["chop"]:
			for i in range(4): assert(game.chop(0.25))
		assert(game.add_carried())
	assert(game.ingredients_complete())
	game.set_heat(0.75)
	for i in range(600):
		game.tick(0.05)
		game.stir(0.01)
		if float(game.session["doneness"]) >= 0.82: break
	assert(float(game.session["doneness"]) >= 0.4)
	for i in range(3): assert(game.plate(0.35))
	assert(game.dish["recipe"] == game.order)
